<?php

declare(strict_types=1);

namespace Route2Api\Exporter;

use Route2Api\IR\ApiEndpoint;
use Route2Api\IR\ApiProject;

final class MarkdownExporter
{
    public function export(ApiProject $project): string
    {
        $lines = [
            '# ' . $project->name,
            '',
            '- Base URL: `' . $project->baseUrl . '`',
            '- Generated by Route2API',
            '',
        ];

        $groups = [];
        foreach ($project->endpoints as $endpoint) {
            $groups[$endpoint->group][] = $endpoint;
        }

        foreach ($groups as $group => $endpoints) {
            $lines[] = '## ' . $group;
            $lines[] = '';

            foreach ($endpoints as $endpoint) {
                $lines = array_merge($lines, $this->endpoint($endpoint));
            }
        }

        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    /**
     * @return string[]
     */
    private function endpoint(ApiEndpoint $endpoint): array
    {
        $lines = [
            '### ' . $endpoint->title,
            '',
            '- Method: `' . $endpoint->method . '`',
            '- Path: `' . $endpoint->path . '`',
        ];

        if ($endpoint->controller !== '') {
            $lines[] = '- Controller: `' . $endpoint->controller . '`';
        }

        if ($endpoint->middlewares !== []) {
            $lines[] = '- Middlewares: `' . implode('`, `', $endpoint->middlewares) . '`';
        }

        if ($endpoint->description !== '') {
            $lines[] = '';
            $lines[] = $endpoint->description;
        }

        if ($endpoint->parameters !== []) {
            $lines[] = '';
            $lines[] = '| Name | In | Type | Required | Description |';
            $lines[] = '| --- | --- | --- | --- | --- |';
            foreach ($endpoint->parameters as $parameter) {
                $lines[] = sprintf(
                    '| `%s` | `%s` | `%s` | %s | %s |',
                    $parameter['name'],
                    $parameter['in'],
                    $parameter['type'],
                    $parameter['required'] ? 'Yes' : 'No',
                    str_replace('|', '\\|', $parameter['description'])
                );
            }
        }

        $lines[] = '';

        return $lines;
    }
}
